#!/usr/bin/python
# vim: syntax=python ts=2 sw=2 sts=2 sr noet
# -*- encoding: utf-8
#
# Date     : 2017-03-17
# Author   : Jodok Ole Glabasna <glabasnj@aschendorff.de>
# Function : Monitor Microsoft Failover Cluster with Check_MK

# This is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation in version 2. This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY; with-
# out even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU General Public License for more de-
# ails. You should have received a copy of the GNU General Public
# License along with GNU Make; see the file COPYING. If not, write
# to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA 02110-1301 USA.

# The inventory function is called with two arguments: the check name and the agent data.
def inventory_av_failovercluster(checkname, info):
	#pprint.pprint(info)
	inventory = []
	for line in info:
		name = line[0]
		inventory.append(('%s' % name, None))
	return inventory

# the check function
def check_av_failovercluster(item, params, info):
	for line in info:
		name  = line[0]
		state = line[1]
		maint = line[2]
		node  = line[3]
		if name == item:
			if maint == "True":
				return (1, "WARN - %s is %s on %s but in Maintenance Mode" % (name, state, node) )
			elif state == "Online":
				return (0, "OK - %s is %s on %s" % (name, state, node) )
			else:
				return (2, "CRIT - %s is %s on %s" % (name, state, node) )
	return (3, "UNKNOWN - This should not happen")

# declare the check to Check_MK
check_info['av_failovercluster']  = {
  "service_description" : "%s",
  "check_function"      : check_av_failovercluster,
  "inventory_function"  : inventory_av_failovercluster,
}

