#!/usr/bin/python

# Jodok Ole Muellers <muellejo@aschendorff.de>
# 31.07.2014

import pprint

# dict to map status code to description
# see /usr/share/snmp/mibs/SNIA-SML-rev1-21.mib
OperationalStatus2desc = {
	0 	:	"unknown",
	1 	:	"other",
	2 	:	"ok",
	3 	:	"degraded",
	4 	:	"stressed",
	5 	:	"predictiveFailure",
	6 	:	"error",
	7 	:	"non-RecoverableError",
	8 	:	"starting",
	9 	:	"stopping",
	10 	:	"stopped",
	11 	:	"inService",
	12 	:	"noContact",
	13 	:	"lostCommunication",
	14 	:	"aborted",
	15 	:	"dormant",
	16 	:	"supportingEntityInError",
	17 	:	"completed",
	18 	:	"powerMode",
	19 	:	"dMTFReserved",
	32768 	:	"vendorReserved",
}

# inventory function
def inventory_ibm_tape_lib_subchassis_status(checkname, info):
	inventory = []
	for subChassisTag, subChassisOperationalStatus in info:
		inventory.append((subChassisTag, None ))
	#pprint.pprint(inventory)
	return inventory 

# check function
def check_ibm_tape_lib_subchassis_status(item, params, info):
	for subChassisTag, subChassisOperationalStatus in info:
		if item == subChassisTag:
			if int(subChassisOperationalStatus) == 2:
				return (0, "OK - Status is %s" % ( OperationalStatus2desc[ int(subChassisOperationalStatus) ] ))
			else:
				return (1, "WARNING - Status is %s" % ( OperationalStatus2desc[ int(subChassisOperationalStatus) ] ))
	return (3, "UNKOWN - something went wrong")

# declare the check to check_mk
#   The check function ( first parameter)
#   The service description for Nagios (second parameter)
#   Has Performance Data 0/1 (third paramter)
#   The inventory function (fourth parameter)
check_info['ibm_tape_lib_subchassis_status'] = (check_ibm_tape_lib_subchassis_status, "Operational Status of %s", 0, inventory_ibm_tape_lib_subchassis_status)

# datasource function
snmp_info['ibm_tape_lib_subchassis_status']  = ( ".1.3.6.1.4.1.14851.3.1.4.10.1", [ '8', '10' ])

snmp_scan_functions['ibm_tape_lib_subchassis_status'] = \
	lambda oid: oid(".1.3.6.1.4.1.2.6.182.3.3.1.0") == "IBM System Storage TS3500 Tape Library"
